@baseUrl = http://localhost:8080/api/capsule

GET {{baseUrl}} HTTP/1.1

###

POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{}

###

POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{
  "capsuleNumber": 1,
  "guestName": "John Doe"
}

###

DELETE {{baseUrl}}/1 HTTP/1.1
